### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by reemardelarosa** [sirajalam049/currency-code-symbol-map#1]
```
export * from './currencyCodeSymbolMapping';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\STARTUP\Zippelin\REPO\zippelin-api\functions\lib\core\util\currency.js:4:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by jun-nguyen-goldenowl** [comment]
I got the same error when running `react-scripts test`

>     Details:

    /Users/qcapollo/repos/GO/pacenow-merchant-portal/node_modules/currency-code-symbol-map/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './currencyCodeSymbolMapping';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import {
        | ^
      2 |   CurrencyCode,
      3 |   currencyCodeSymbolMapping,
      4 | } from 'currency-code-symbol-map';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1327:14)
      at Object.<anonymous> (src/utils/converters/currencyCode2Symbol.ts:1:1)

**Comment by jokopoppo** [comment]
2021 still stuck in this

**Comment by sirajalam049** [comment]
Hi @reemardelarosa, please add the steps to reproduce.
